apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: nextcloud
  labels:
    app: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      serviceAccountName: postgres
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        runAsNonRoot: true
        fsGroup: 999
      terminationGracePeriodSeconds: 60
      containers:
        - name: postgres
          image: postgres:16-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: postgres
              protocol: TCP
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_INITDB_ARGS
              value: '--auth-host=scram-sha-256'
            - name: POSTGRES_HOST_AUTH_METHOD
              value: 'scram-sha-256'
            - name: POSTGRES_CONFIG_FILE
              value: '/etc/postgresql/postgresql.conf'
          resources:
            requests:
              memory: '256Mi'
              cpu: '100m'
              ephemeral-storage: '256Mi'
            limits:
              memory: '512Mi'
              cpu: '500m'
              ephemeral-storage: '1Gi'
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -h localhost -U "$POSTGRES_USER" -d "$POSTGRES_DB"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -h localhost -U "$POSTGRES_USER" -d "$POSTGRES_DB"
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: postgres-config
              mountPath: /etc/postgresql/postgresql.conf
              subPath: postgresql.conf
              readOnly: true
      volumes:
        - name: postgres-config
          configMap:
            name: postgres-config
            items:
              - key: postgresql.conf
                path: postgresql.conf
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: nextcloud
  labels:
    app: postgres
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: nextcloud
spec:
  schedule: '0 2 * * *'
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: postgres-backup
        spec:
          serviceAccountName: postgres-backup
          automountServiceAccountToken: false
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 1000
          containers:
            - name: backup
              image: postgres:16-alpine
              imagePullPolicy: IfNotPresent
              env:
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: POSTGRES_PASSWORD
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: POSTGRES_USER
                - name: POSTGRES_DB
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: POSTGRES_DB
                - name: POSTGRES_HOST
                  value: postgres
                - name: BACKUP_RETENTION_DAYS
                  value: '7'
              command:
                - /bin/sh
                - -c
                - |
                  set -euo pipefail
                  BACKUP_DIR="/var/lib/postgresql/backups"
                  mkdir -p "$BACKUP_DIR"
                  TIMESTAMP=$(date +%Y%m%d_%H%M%S)
                  BACKUP_FILE="$BACKUP_DIR/nextcloud_backup_$TIMESTAMP.sql.gz"

                  echo "Starting backup at $(date)"
                  if pg_dump -h "$POSTGRES_HOST" -U "$POSTGRES_USER" -d "$POSTGRES_DB" | gzip > "$BACKUP_FILE"; then
                    echo "Backup completed: $BACKUP_FILE"
                    gzip -t "$BACKUP_FILE" && echo "Backup verified"
                    find "$BACKUP_DIR" -name "nextcloud_backup_*.sql.gz" -type f -mtime +$BACKUP_RETENTION_DAYS -delete
                    echo "Old backups cleaned"
                  else
                    echo "ERROR: Backup failed!" >&2
                    exit 1
                  fi
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: false
                capabilities:
                  drop:
                    - ALL
              resources:
                requests:
                  memory: '128Mi'
                  cpu: '50m'
                  ephemeral-storage: '256Mi'
                limits:
                  memory: '256Mi'
                  cpu: '100m'
                  ephemeral-storage: '512Mi'
              volumeMounts:
                - name: postgres-backup
                  mountPath: /var/lib/postgresql/backups
          volumes:
            - name: postgres-backup
              persistentVolumeClaim:
                claimName: postgres-backup-pvc
          restartPolicy: OnFailure
