apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-pvc
  namespace: nextcloud
  labels:
    app: nextcloud
  annotations:
    argocd.argoproj.io/sync-options: Replace=false
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backup-pvc
  namespace: nextcloud
  labels:
    app: postgres-backup
  annotations:
    argocd.argoproj.io/sync-options: Replace=false
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
