apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: nextcloud
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:H5ESd8ikOjy1,iv:EwWY3tzFtMlNL7z883xsGYqVIagoJxOL0SSvY7A+YZg=,tag:76xqlETrmcCNgbgQzUdTXQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Zll5yTNG0LK9,iv:TxXo6uw+St0OAzPVWLa7T21sdc1zOdJK/UeMWyeyy3U=,tag:lIRtWzLV4hlXvQQmp5A/4Q==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:VZj6erYPIOSS,iv:1Qn+xPChCH9pwh1wDKT22Q0Jo8F4i3INmFF3hH2RXO4=,tag:yuN7p2TaCTMuiVimKNTgoQ==,type:str]
sops:
    age:
        - recipient: age13gwk9j9ddstm8ss9n2u8nx6ruh6zgafsapepmjz353tuarwu23hsqffl6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTnVLVHl1eHR3QTdkbFlt
            WlFwMTh1cTRrWXhVci93OThuWEd0RmlHekZrCmNYODdzYVY1Nm9yOUZ0MHFHTmJR
            dENhWEoyUkFsMVBvWWl6N1lZZkxlYkUKLS0tIFpFVS9wTDFrYklFTDUzTVJMVnBM
            azlVZXM2Vy9iNjhiSFJNMTU4S3FneWMK6rUQz2DsbwGdAXQB7NJYhMgC4Z0aUrVc
            lpuuUrWLJ527IIBp9/kZW2C7mg8nEeLgvWqd3RsSGcxZvT+J3G4EaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T19:23:14Z"
    mac: ENC[AES256_GCM,data:X3RGTGQCpYyIcfz+H6FeYlgr0uEL2YxNXWKPCNsgWARDqv2nPtMwAXCOFqfNGOxsdmSnIhCnQfDLM96yVMOrHAS8wy51pYnFYk1G9SG8eQUaTxogdtLd+CTFjkU7iFNIbtU7GT+3f1VMamL40LeL5ArgdQOEfmtHzIL8aola3vk=,iv:4q7OkWgy3hjuMo7oW8JYqOl6J5K06g69RdNwTp/arfs=,tag:D4r/dFo1jtPw/sRukFAlbA==,type:str]
    encrypted_regex: ^(data|stringData|password|token|key|secret|apiKey|apiToken|credential)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secret
    namespace: nextcloud
type: Opaque
stringData:
    NEXTCLOUD_ADMIN_USER: ENC[AES256_GCM,data:GuitvMM=,iv:kWmrqokKzbcIxyMg32empCf3EbT/MXw1CSts5+TB46U=,tag:FV3cVylAeV9nkg3jXCq0/A==,type:str]
    NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:mLdDlpc=,iv:zxBePwlBA9IVRikUGIyiTm1TXdJytB3qXUbsKzn2szE=,tag:/Ysfvkn7HKOce+5UItA4Dg==,type:str]
sops:
    age:
        - recipient: age13gwk9j9ddstm8ss9n2u8nx6ruh6zgafsapepmjz353tuarwu23hsqffl6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTnVLVHl1eHR3QTdkbFlt
            WlFwMTh1cTRrWXhVci93OThuWEd0RmlHekZrCmNYODdzYVY1Nm9yOUZ0MHFHTmJR
            dENhWEoyUkFsMVBvWWl6N1lZZkxlYkUKLS0tIFpFVS9wTDFrYklFTDUzTVJMVnBM
            azlVZXM2Vy9iNjhiSFJNMTU4S3FneWMK6rUQz2DsbwGdAXQB7NJYhMgC4Z0aUrVc
            lpuuUrWLJ527IIBp9/kZW2C7mg8nEeLgvWqd3RsSGcxZvT+J3G4EaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T19:23:14Z"
    mac: ENC[AES256_GCM,data:X3RGTGQCpYyIcfz+H6FeYlgr0uEL2YxNXWKPCNsgWARDqv2nPtMwAXCOFqfNGOxsdmSnIhCnQfDLM96yVMOrHAS8wy51pYnFYk1G9SG8eQUaTxogdtLd+CTFjkU7iFNIbtU7GT+3f1VMamL40LeL5ArgdQOEfmtHzIL8aola3vk=,iv:4q7OkWgy3hjuMo7oW8JYqOl6J5K06g69RdNwTp/arfs=,tag:D4r/dFo1jtPw/sRukFAlbA==,type:str]
    encrypted_regex: ^(data|stringData|password|token|key|secret|apiKey|apiToken|credential)$
    version: 3.11.0
