# Nextcloud Secrets - ENCRYPT WITH SOPS BEFORE COMMITTING!
#
# To encrypt: sops -e -i nextcloud/base/secrets.yaml
# To edit:    sops nextcloud/base/secrets.yaml
#
apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: nextcloud
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:mQ7DcGzfpyCn,iv:HG2BT9b6DaslZ6kVQnusF5sZQcbojW2EFf39D7hRJeY=,tag:BMVmXOXLHVU3cOLl3U7ZKQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:KHB2d862/VckARvIYBw8wD/ZedH0LABEUB+hwvQJYZubYZAHrSuoZi8CXqg=,iv:3vlry1UvtGJSc/qWTLpTsZiDoq2s/DMC65ezZww7Rm8=,tag:aiddRbErgLP2Lu1+8mANpg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:sTjJ1ZVggZyN,iv:7zEH4fvea9NomzX2a6cwBZOKe4qBvSGxsoR48gdmlOs=,tag:aymNdpYWBHaZtV96mR4pfg==,type:str]
sops:
    age:
        - recipient: age12w6hdx8fxq5g7x6x6ujh9ve6je4tlq0m9rhyrrt20vcjhzwkmqvsgfwk9u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUmJhUVNQbWd4NEpJREEx
            MmxKT1VuOGJEN1RSTWdOY3crdUtJUUQzVjFFCnZKUGdIOW9hYnBKYjlOM0c5NGh6
            eG42K0V3cnZEMHFZSGM1bGlYdkFoRWcKLS0tIExTT0FZdHVkLzljcS9NL3YrVnpN
            N0N3SC9QS3dJVS81bUliamtFYjBYeEUKkYc5EatEpUp+WctzF6x64ML1nA7Wg3tQ
            YHEdfxv12vmH/RsroTo2j9JzbI0FijdL7t4iTiqCNaEO3HzkbMt6bA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T20:53:19Z"
    mac: ENC[AES256_GCM,data:34FAThs36zfoDcwOSwXfHTXnfAmy1nVahvyeECi08rKNRptC/TYO27YOAwq2w7qFaADAO3d2C7LAZ8ur60uEgZorF3stO1ljmmpVxC6gzUiBKfaZLyPHOtQlwAHiFpjTDF9mI0UuthSDet473Uq3gG2VsN7bCEirlEwEUhiHjHY=,iv:IcX/mC6MFu0B7BNsSZ3Do0znAWUleoMYMe7FfXypfIA=,tag:ww6/t5cVX1PWm4a11z4+0A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secret
    namespace: nextcloud
type: Opaque
stringData:
    NEXTCLOUD_ADMIN_USER: ENC[AES256_GCM,data:fHyd9iY=,iv:eHMfLKB7zTf2mLT8zL0euF4AlQoiSFNoLWwIDSYMUOA=,tag:o9kUjbJryWE5xlXHCXiuZw==,type:str]
    NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:0RwqtYSJCf6rqIMn8AWGZrbosWSGAYr9N246AA2WNReA5cEcFyDArINerL4=,iv:LK/AwgWzEN4F9j2lGAoyqvcn3yQ75jGkrDTyQJzN9ww=,tag:DGFfY1cEMD6pHbaN2rmtvA==,type:str]
sops:
    age:
        - recipient: age12w6hdx8fxq5g7x6x6ujh9ve6je4tlq0m9rhyrrt20vcjhzwkmqvsgfwk9u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUmJhUVNQbWd4NEpJREEx
            MmxKT1VuOGJEN1RSTWdOY3crdUtJUUQzVjFFCnZKUGdIOW9hYnBKYjlOM0c5NGh6
            eG42K0V3cnZEMHFZSGM1bGlYdkFoRWcKLS0tIExTT0FZdHVkLzljcS9NL3YrVnpN
            N0N3SC9QS3dJVS81bUliamtFYjBYeEUKkYc5EatEpUp+WctzF6x64ML1nA7Wg3tQ
            YHEdfxv12vmH/RsroTo2j9JzbI0FijdL7t4iTiqCNaEO3HzkbMt6bA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T20:53:19Z"
    mac: ENC[AES256_GCM,data:34FAThs36zfoDcwOSwXfHTXnfAmy1nVahvyeECi08rKNRptC/TYO27YOAwq2w7qFaADAO3d2C7LAZ8ur60uEgZorF3stO1ljmmpVxC6gzUiBKfaZLyPHOtQlwAHiFpjTDF9mI0UuthSDet473Uq3gG2VsN7bCEirlEwEUhiHjHY=,iv:IcX/mC6MFu0B7BNsSZ3Do0znAWUleoMYMe7FfXypfIA=,tag:ww6/t5cVX1PWm4a11z4+0A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
