apiVersion: v1
kind: ServiceAccount
metadata:
  name: nextcloud
  namespace: nextcloud
  labels:
    app: nextcloud
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
  namespace: nextcloud
  labels:
    app: postgres
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-backup
  namespace: nextcloud
  labels:
    app: postgres-backup
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis
  namespace: nextcloud
  labels:
    app: redis
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nextcloud-cron
  namespace: nextcloud
  labels:
    app: nextcloud-cron
